const String PREF_DTMF_TONE = "PREF_DTMF_TONE";
const String PREF_DIALPAD_VIBRATION = "PREF_DIALPAD_VIBRATION";
const String PREF_DIALPAD_LETTERS = "PREF_DIALPAD_LETTERS";

const String PREF_MATERIAL_THEMING = "PREF_MATERIAL_THEMING";
const String PREF_AMOLED_DARK_MODE = "PREF_AMOLED_DARK_MODE";
const String PREF_SHOW_FIRST_LETTER = "PREF_SHOW_FIRST_LETTER";
const String PREF_SHOW_PICTURE_IN_AVATAR = "PREF_SHOW_PICTURE_IN_AVATAR";
const String PREF_ICON_ONLY_BOTTOMSHEET = "PREF_ICON_ONLY_BOTTOMSHEET";
const String PREF_ALWAYS_SHOW_SELECTED_IN_BOTTOMSHEET =
    "PREF_ALWAYS_SHOW_SELECTED_IN_BOTTOMSHEET";

const String PREF_DEFAULT_SIM = "PREF_DEFAULT_SIM";
